python generate_data.py \
    --model=resnet20_cifar100 \
    --teacher_checkpoint=/path/to/resnet20_cifar100_teacher.pth \
    --dataset_path=/path/to/imagenet \
    --output_dir=../data/cifar100 \
    --file_prefix=resnet20_cifar100_unified_curated \
    --subset_size=500000 \
    --batch_size=128 \
    --num_augmentations=5 \
    --w_sens=0.5 \
    --w_pot=0.5 \
    --samples_per_class=50 \
    --num_groups=4
