python generate_data.py \
    --model=resnet18 \
    --dataset_path=/path/to/imagenet \
    --output_dir=../data/imagenet \
    --file_prefix=imagenet_unified_curated \
    --subset_size=500000 \
    --batch_size=128 \
    --num_augmentations=5 \
    --w_sens=0.5 \
    --w_pot=0.5 \
    --samples_per_class=50 \
    --num_groups=4
